local _, ns = ...

local L = {
	APP_TITLE = "Better Control Vendor",
	APP_SUBTITLE = "Handheld vendor flow built for Ally and Xbox-style layouts.",
	BUY = "Buy",
	SELL = "Sell",
	BUYBACK = BUYBACK or "Buyback",
	REPAIR = REPAIR or "Repair",
	FILTER_ALL = ALL or "All",
	FILTER_CONSUMABLES = CONSUMABLES or "Consumables",
	FILTER_REAGENTS = "Reagents",
	FILTER_LIMITED = "Limited",
	FILTER_AFFORDABLE = "Affordable",
	MODE_PURCHASE = "Purchase",
	MODE_TOTAL = "Inventory Target",
	OWNED = "Owned",
	VENDOR_STOCK = "Vendor",
	BUNDLE = "Bundle",
	PRICE = PRICE or "Price",
	START_PURCHASE = "Start Purchase",
	QUEUE_CANCEL = CANCEL or "Cancel",
	STATUS_IDLE = "Ready",
	STATUS_NO_SELECTION = "Select an item to configure a purchase target.",
	STATUS_SELL_EMPTY = "No sellable items in bags.",
	STATUS_BUYBACK_EMPTY = "Nothing available in buyback.",
	STATUS_REPAIR_IDLE = "Repair controls are ready.",
	SELL_ONE = "Sell One",
	SELL_STACK = "Sell Stack",
	SELL_SELECTED = "Sell Selected",
	SELL_JUNK = "Sell Junk",
	TOGGLE_SELECT = "Toggle",
	REPAIR_EQUIPPED = "Repair Equipped",
	REPAIR_ALL = "Repair All",
	REPAIR_GUILD = "Guild Repair",
	QUEUE_TARGET = "Queue Target",
	QUEUE_PROGRESS = "Progress",
	QUEUE_PENDING = "Pending",
	QUEUE_DONE = "Done",
	QUEUE_STOPPED = "Stopped",
	DEVICE_PROFILE = "Input",
	ALLY_LAYOUT = "Ally / Xbox",
	MOUSE_LAYOUT = "Mouse / Keyboard",
	WARNING_PURCHASE = "Start a vendor purchase for %s?",
	CONFIRM_WARNING = "This target will be executed in controlled batches. Confirm to continue.",
	NOT_ENOUGH_SPACE = "No empty bag slot for single-item split.",
}

ns.L = L

ns.SkinTokens = {
	frame = {
		width = 760,
		height = 554,
	},
	list = {
		rowHeight = 46,
		visibleRows = 8,
		icon = 30,
	},
	panels = {
		leftWidth = 420,
		rightWidth = 278,
	},
	colors = {
		accent = { 1.0, 0.82, 0.1 },
		success = { 0.3, 0.9, 0.3 },
		warning = { 1.0, 0.55, 0.1 },
		danger = { 1.0, 0.25, 0.25 },
		muted = { 0.72, 0.72, 0.72 },
		panel = { 0.08, 0.08, 0.08, 0.85 },
		row = { 0.12, 0.12, 0.12, 0.55 },
		rowActive = { 0.22, 0.18, 0.06, 0.95 },
		consumable = { 0.0, 0.8, 1.0, 0.85 },
	},
}
